name: Cloudbase-Init build MSI

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-2016
    strategy:
      max-parallel: 100
      matrix:
        cbsinit_repo: ['https://github.com/rgl/cloudbase-init']
        cbsinit_branch:
          - master
          - add-no-cloud

    steps:
    - uses: actions/checkout@v1
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: Build msi
      shell: cmd
      run: |
        powershell.exe .\BuildAutomation\BuildCloudbaseInitSetup.ps1^
            -ClonePullInstallerRepo:$false -CreateZip:$false ^
            -SetVCEnvVars:$false -RelativePythonDirPath^
            -CloudbaseInitRepoUrl ${{ matrix.cbsinit_repo }} -CloudbaseInitRepoBranch ${{ matrix.cbsinit_branch }}
    - uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.cbsinit_branch }} msi
        path: CloudbaseInitSetup/bin/Release/x64/CloudbaseInitSetup.msi
