name: CI
on: [push]
jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v1
    - name: Dump Environment
      shell: powershell
      run: |
        $FormatEnumerationLimit = -1
        function Write-Title($title) {
          Write-Output "`n#`n# $title`n#"
        }
        Write-Title "whoami"
        cmd /c "whoami /all"
        Write-Title "Windows version"
        cmd /c ver
        Write-Title "Environment Variables"
        dir env: `
          | Format-Table -AutoSize `
          | Out-String -Stream -Width ([int]::MaxValue) `
          | ForEach-Object {$_.TrimEnd()}
        Write-Title "TimeZone"
        Get-TimeZone
